// @ts-check
import { defineConfig } from 'astro/config'
import starlight from '@astrojs/starlight'
import starlightOpenAPI, { openAPISidebarGroups } from 'starlight-openapi'

// https://astro.build/config
export default defineConfig({
	// Custom domain served at the root, so no `base` path is needed.
	site: 'https://docs.hydrate.sh',
	integrations: [
		starlight({
			title: 'hydrate.sh',
			logo: {
				src: './src/assets/logo.png',
				alt: 'hydrate.sh droplet mark',
			},
			favicon: '/favicon.png',
			customCss: ['./src/styles/brand.css'],
			social: [
				{
					icon: 'github',
					label: 'GitHub',
					href: 'https://github.com/hydrate-sh',
				},
			],
			plugins: [
				// Generates the API-reference section from the committed
				// OpenAPI spec (synced from the app repo's
				// backend/openapi.json — see README "Keeping the API
				// reference in sync").
				starlightOpenAPI([
					{
						base: 'api/v1',
						label: 'API reference',
						schema: './openapi.json',
					},
				]),
			],
			sidebar: [
				{
					label: 'Getting started',
					items: [
						{ label: 'Introduction', slug: 'getting-started/introduction' },
						{ label: 'Authentication', slug: 'getting-started/authentication' },
					],
				},
				// API-reference groups generated by starlight-openapi.
				...openAPISidebarGroups,
			],
		}),
	],
})
